version: '3.7'

services:
  app:
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - "5000:5000"
    environment:
     - FLASK_ENV=development
     - APP_SETTINGS=config.DevelopmentConfig
     - DATABASE_URL=mysql://wallet_user:wallet_pw@db/crypto
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3207:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wallet_user
      MYSQL_PASSWORD: wallet_pw
      MYSQL_DATABASE: crypto
