"""empty message

Revision ID: 03131dfde5d2
Revises: 
Create Date: 2020-02-20 02:49:07.565109

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '03131dfde5d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('email', sa.String(length=256), nullable=False),
                    sa.Column('password', sa.String(length=128), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('crypto_wallet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=256), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['crypto_user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_wallet')
    op.drop_table('crypto_user')
    # ### end Alembic commands ###
