"""empty message

Revision ID: 436a025a7689
Revises: fb9f039ee527
Create Date: 2020-02-20 22:01:42.250402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '436a025a7689'
down_revision = 'fb9f039ee527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_transaction',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_transferred', sa.Integer(), nullable=False),
                    sa.Column('transferred_value', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['crypto_user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_transferred'], ['crypto_user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('user_transferred', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('transferred_value', mysql.FLOAT(), nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['crypto_user.id'], name='transaction_ibfk_1',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_transferred'], ['crypto_user.id'], name='transaction_ibfk_2',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.drop_table('crypto_transaction')
    # ### end Alembic commands ###
